# Generated by Django 3.2.2 on 2021-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preschool_Play', '0003_auto_20210509_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='uploads/uploads'),
        ),
    ]
