# Generated by Django 3.2 on 2021-04-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preschool_Play', '0003_message_is_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
