# Generated by Django 3.2.2 on 2021-05-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preschool_Play', '0013_alter_videos_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'video', 'verbose_name_plural': 'video'},
        ),
    ]
