# Generated by Django 3.2.2 on 2021-05-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preschool_Play', '0015_auto_20210510_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preschool_Play.userprofile'),
        ),
    ]
