pipeline {
    agent {
        docker {
            image 'python:3.8-buster'
        }
    }
    stages
    {
        stage('Build')
        {
            steps {
                    sh 'python --version'
            }
        }
        stage('setup')
        {
            steps
            {
                withEnv(["HOME=${env.WORKSPACE}"])
                {
                    dir('jenkins')
                    {
                        sh 'python -m pip install -r requirements.txt'
                    }
                     echo 'hello'
                }
            }
        }
        stage('Test')
        {
            agent
            {
                docker
                 {
                    image 'qnib/pytest'
                 }
            }
            steps {
                sh 'py manage.py test Preschool_Play/tests.py'
            }
        }
    }
}