pipeline {
    agent { docker { image 'python:3.8-buster' } }
    triggers {
      githubPush()
  }

    stages {
        stage('Build') {
            steps {
                sh 'python --version'
            }

        }
        stage('setup'){
          steps{
            withEnv(["HOME=${env.WORKSPACE}"]){

            dir('jenkins'){
            sh 'python -m pip install -r requirements.txt'
            }
            echo 'hello'
          }
          }
        }
          stage('Run Unit Tests') {
                steps {
            dir('./') {
              withEnv(["HOME=${env.WORKSPACE}"]) {
              sh """
                #!/bin/bash
                cd BS_PM2021_TEAM_27
                ls
                python manage.py makemigrations
                python manage.py migrate
                python -m coverage run manage.py test --tag=unit-test
                """
              }
            }
          }
            }
    }

}