pipeline {
    agent none
    stages {
        stage('build') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps {
                sh '''
                    python -m venv .venv
                    . .venv/bin/activate
                    pip install -r backend/requirements.txt
                '''
            }
        }
        stage('test') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps {
                 sh '''
                    python -m venv .venv
                    . .venv/bin/activate
                    pip install -r backend/requirements.txt
                    python backend/test.py
                    py manage.py test
                    Preschool_Play/tests.py
                '''
            }
        }
    }
}