pipeline {
    agent { dockerfile true }
    triggers {
      githubPush()
  }

    stages {

        stage('Run Unit Tests') {
          steps {
              sh """
                  py manage.py test
              """
          }
        }
    }

}