pipeline {
    environment {
        EMAIL_USE_TLS = True
        EMAIL_HOST = 'smtp.gmail.com'
        EMAIL_HOST_USER = 'shamooncinemas@gmail.com'
        EMAIL_HOST_PASSWORD = 'p3xakFwr'
        EMAIL_PORT = 587
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_USE_SSL = False
        OUTPUT1 = "foo"
    }
    agent {
        docker { image 'eilonc285/repos-team27:team27' }
    }
    triggers {
        githubPush()
    }
    stages {
        stage('Build') {
            steps {
                sh """
                    cd BS_PM2021_TEAM_27
                    python manage.py makemigrations
                    python manage.py migrate
                """
            }
        }
        stage('Run Unit Tests') {
            steps {
                dir("BS_PM2021_TEAM_27"){
                    script{
                        try{
                            sh(returnStdout: true, script: "python manage.py test Preschool_Play.tests.TestInboxView 2>&1 | xargs echo > out1.txt")
                        }finally{
                            OUTPUT1 = sh(returnStdout: true, script: "cat out1.txt")
                        }
                    }
                }
            }
        }
    }
    post{
        always{
            echo '99999999999999999999999999'
            echo OUTPUT1
            dir("BS_PM2021_TEAM_27"){
                sh """
                     python manage.py email_report -s "Tests Report" -b "${OUTPUT1}"
                """
            }
            sh "cat out1.txt"
        }
    }
}