pipeline {
    agent { dockerfile true }
    triggers {
      githubPush()
  }

    stages {

        stage('Run Unit Tests') {
          steps {
              sh """
                  python BS_PM2021_TEAM_27/manage.py test BS_PM2021_TEAM_27
              """
          }
        }
    }

}